version: '3.8'

services:
  backend:
    container_name: phd-backend
    build:
      context: .
      dockerfile: SimulatedAnnealing.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__PhdApi=Server=host.docker.internal;Database=PhdApi;TrustServerCertificate=True;
    
  frontend:
    container_name: phd-frontend
    build:
      context: C:/Users/matja/source/repos/simmulated-annealing-front/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
